# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ref-engine
  labels:
    app: ref
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ref
  template:
    metadata:
      labels:
        app: ref
    spec:
      containers:
        - name: ref-container
          image: registry.heroku.com/{{HEROKU_APP_NAME}}/web
          ports:
            - containerPort: 5001
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: GITHUB_SHA
              value: "{{GITHUB_SHA}}"
---

# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ref-engine-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ref-engine
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---

# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ref-service
spec:
  type: LoadBalancer
  selector:
    app: ref
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001

---

# k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ref-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: ref.yourdomain.com  # <-- Replace with your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ref-service
                port:
                  number: 80
  tls:
    - hosts:
        - ref.yourdomain.com
      secretName: ref-tls-cert

---

# k8s/cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jlanders1005@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: nginx
