 (cd "$(git rev-parse --show-toplevel)" && git apply --3way <<'EOF' 
diff --git a//dev/null b/k8s/ingress.yaml
index 0000000000000000000000000000000000000000..3e01abeb58c30f703d5e4f60980996fead46ec0b 100644
--- a//dev/null
+++ b/k8s/ingress.yaml
@@ -0,0 +1,24 @@
+apiVersion: networking.k8s.io/v1
+kind: Ingress
+metadata:
+  name: ref-ingress
+  annotations:
+    nginx.ingress.kubernetes.io/rewrite-target: /
+    nginx.ingress.kubernetes.io/ssl-redirect: "true"
+    cert-manager.io/cluster-issuer: letsencrypt-prod
+spec:
+  rules:
+    - host: ref.yourdomain.com  # <-- Replace with your actual domain
+      http:
+        paths:
+          - path: /
+            pathType: Prefix
+            backend:
+              service:
+                name: ref-service
+                port:
+                  number: 80
+  tls:
+    - hosts:
+        - ref.yourdomain.com
+      secretName: ref-tls-cert
 
EOF
)
