name: 🚀 Deploy REF to IBM Cloud Kubernetes

on:
  push:
    branches: [ "main" ]

env:
  IBM_CLOUD_REGION: us-south
  REGISTRY_HOSTNAME: us.icr.io
  IMAGE_NAME: ref-sareth
  DEPLOYMENT_NAME: ref-engine
  SERVICE_NAME: ref-service
  PORT: 5001
  SERVICE_PORT: 80
  IKS_CLUSTER: ref-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: 📦 Checkout Repo
        uses: actions/checkout@v4

      - name: 🔧 Install IBM Cloud CLI & Plugins
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install -f kubernetes-service
          ibmcloud plugin install -f container-registry

      - name: 🔑 IBM Cloud Login
        run: |
          ibmcloud login --apikey "$IBM_CLOUD_API_KEY" -r "$IBM_CLOUD_REGION" -g default
          ibmcloud cr region-set "$IBM_CLOUD_REGION"
          ibmcloud cr login
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}

      - name: 🛠 Build and Push Docker Image
        run: |
          docker build -t $REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA .
          docker push $REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA
        env:
          ICR_NAMESPACE: ${{ secrets.ICR_NAMESPACE }}

      - name: 🚀 Deploy to Kubernetes
        run: |
          ibmcloud ks cluster config --cluster $IKS_CLUSTER
          kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA
          kubectl rollout status deployment/$DEPLOYMENT_NAME

      - name: ❌ Handle Failure
        if: failure()
        run: echo "Deployment failed. Check IBM Cloud logs and image rollout."
