# Root-level example secrets file
# Copy this to `.streamlit/secrets.toml` and replace with your real keys.

# Preferred default OpenAI API key
OPENAI_API_KEY = "sk-your-real-key-here"

# Optional fallback formats:
[openai]
api_key = "sk-your-openai-key"

[serith]
api_key = "sk-your-serith-key"

